name: CI
on:
  push:
    branches: [ main ]
jobs:
  build_test_api:
    name: Building and Testing API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          npm install
          npm ci  

      - name: Run Unit Tests
        run: |
          npm run test

  build_test_frontend:
    name: Building and Testing Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install
          npm ci    

      - name: Run Unit Test - Build Application
        run: |
          npm run test
          npm run build

  push_to_Docker_Hub:
    runs-on: ubuntu-latest
    needs: [build_test_api, build_test_frontend]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build The Stack
        run: docker-compose up -d

      - name: Test The Stack
        run: docker run --network container:api_c appropriate/curl -s --retry 10 --retry-connrefused http://localhost:4000/     